### ISSUE TITLE
Fix print style for LibraryH3lp FAQ

### ISSUE THREAD

**Issue by tomkeays** [tomkeays/lemoyne#39]
This ought to do it -- add to `right-sidebar.html` template: 
```css
@media print {
  #s-lg-tabs-container {
    display: none;
  }
}
```
